version: 2
updates:
  - package-ecosystem: npm
    directory: /src/frontend/maskflow-web
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns: ["*"]

  - package-ecosystem: nuget
    directory: /src/backend/maskflow-api
    schedule:
      interval: weekly
    groups:
      backend-dependencies:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /src/ai/sam-inference
    schedule:
      interval: weekly
    groups:
      inference-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
